### PR TITLE
Clarify status code URL

### PR DESCRIPTION
**Pull request by wesinator**

### CODE REVIEW

**Comment by citricsquid** [comment]
@wesinator Hi Wes, thank you for the contribution, unfortunately it's unlikely to be accepted. Please refer to the following comment from February: https://github.com/rmaake1/httpstatuses/pull/64#issuecomment-466788195

**Comment by wesinator** [comment]
> @wesinator Hi Wes, thank you for the contribution, unfortunately it's unlikely to be accepted. Please refer to the following comment from February: [#64 (comment)](https://github.com/rmaake1/httpstatuses/pull/64#issuecomment-466788195)

Ok, could you archive this repo then ?

**Comment by citricsquid** [comment]
@wesinator I no longer have any control over the repository nor do I believe the repository owner monitors these issues, you'll need to reach out to the company to make that request.

**Comment by wesinator** [comment]
cc @rmaake1

**Pull request closed without merging**
